### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by supki** [supki/directory-layout#5]
Folks express interest in having directory-layout working on Windows, too

**Comment by supki** [comment]
@dmalikov, could you take a look at what subset (?) of functionality we can reliably implement for unix-likes and windows both?

**Comment by dmalikov** [comment]
Just a minor note: it should be something like "cygwin support" because of huge variety of possible ghc environments in Windows system. Thus the point of the task is to get rid of `unix` package dependency and substitute all `Posix` stuff with something cygwin-compatible. 

I'm not sure about subset (?) of functionality that will be impossible to implement without `Posix` stuff. Finding this subset is actually what this task is about :)

**Comment by supki** [comment]
Apparently, it's possible to install `unix` package on Windows using Cygwin tools, and we do not do anything especially Windows-hostile besides depending on `unix` in `directory-layout`, so Windows support should be a non-issue. Please reopen if I'm missing anything!
